# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The PyRoll Project
email: kalibrierzentrum@imf.tu-freiberg.de
description: >-
  PyRoll is an OpenSource rolling framework, aimed to provide a fast and extensible base for rolling simulation.
  The current focus lies on groove rolling in elongation grooves.
  The core packages comes with a basic set of models to allow a first estimation of forces and torques occurring in a pass sequence.
  There is a flexible plugin system, able to modify and extend the model set available to describe the process.
baseurl: ""
url: ""
github_username: pyroll-project

# Build settings
remote_theme: jekyll/minima
plugins:
  - github-pages

header_pages:
  - about.md

titles_from_headings:
  enabled:     true
  strip_title: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
